version: "3.9"
services:
  db:
    image: postgres:16
    container_name: beatbox-postgres
    environment:
      POSTGRES_USER: beatbox
      POSTGRES_PASSWORD: beatbox
      POSTGRES_DB: beatbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beatbox"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data_dev:
